version: '3.7'

services:
  db:
    container_name: "bookstore_db"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: <PASS>
      MYSQL_DATABASE: <DBNAME>
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    container_name: "bookstore_api"
    build:
       context: .
       dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app/


networks:
  default:
volumes:
  mysql_data:
